### ISSUE TITLE
It can't be connected properly on arch linux

### ISSUE THREAD

**Issue by WE1ZARD** [ITotalJustice/ftpsrv#2]
FW: 18.0.1
AMS: 1.8.0

App Version: 0.1.2

![image](https://github.com/user-attachments/assets/c5c3f1aa-6237-4ba9-815a-750df8e4ba88)

![image](https://github.com/user-attachments/assets/1765f447-b1a6-4d40-af57-723590318fe0)

Either sysmodule or application can't be connected on my pc since v0.1.0,
but i was able to connect with [sys-ftpd-light](https://github.com/Genwald/sys-ftpd-light).

Latest version sysmodule and app both are working fine on my iphone via ftpmanager.

Thank you so much for sharing these amazing tools, absolutely love it, especialy sphaira.

**Comment by WE1ZARD** [comment]
FW 19.0.1
AMS: 1.8.0

Platform: Arch Linux, Windows

Tried port 21, 1000, 212, didn't work out, same results.
![20241128125952](https://github.com/user-attachments/assets/038f3c89-cc96-4ce9-b289-12ab5ab49e08)

**Comment by ITotalJustice** [comment]
What is the name of the FTP client used on arch Linux?

**Comment by WE1ZARD** [comment]
> What is the name of the FTP client used on arch Linux?

![image](https://github.com/user-attachments/assets/6f4764b8-6d9f-4130-b3ac-071b5a855f91)
it comes with gnome desktop.
for first time,
I will input `ftp://192.168.50.8:5000` for sftp-light and it will mount to my pc after connected,
I did exactly same step for ftpsrv and sftp-light,

**sftp-light succeed**
![image](https://github.com/user-attachments/assets/e2a53e83-1a82-4c6d-a31f-f6b59e655cef)

**ftpsrv failed**
![image](https://github.com/user-attachments/assets/858c1a33-5aa1-4e64-b10c-50c9ba8e2279)

i tried [`gftp client` ](https://aur.archlinux.org/packages/gftp)  today with port 21, 1000 and all failed.

**Comment by WE1ZARD** [comment]
platform: windows 11 pro
system version: 23h2

ftpsrv version: 0.1.2
ftp client: filezilla

also failed, this one from my friend.

**Comment by ITotalJustice** [comment]
Thank you for testing this further. I am surprised that FileZilla is having problems, that is the client that I did all my testing on.

I will look into this when I finish work. I'll fix it either tonight or tomorrow 👍🏼

**Comment by ITotalJustice** [comment]
are you available on discord? i cannot reproduce the bugs youre facing so i have created a build with logging. but it would be a bit easier / quicker if we could talk via discord. ill report the issue / fix back on the issue as to track it.

**Comment by WE1ZARD** [comment]
> are you available on discord? i cannot reproduce the bugs youre facing so i have created a build with logging. but it would be a bit easier / quicker if we could talk via discord. ill report the issue / fix back on the issue as to track it.

yes, no problem. 
my dc id: `.we1zard`
or send me an invite link if u perfer dc channel.
