### ISSUE TITLE
Sys-module crashes when accessed with rclone

### ISSUE THREAD

**Issue by krasmazov483** [ITotalJustice/ftpsrv#3]
I've been trying to use rclone to sync my RetroArch, PPSSPP and MelonDS saves automatically from my Switch to my PC for the past couple of days but it crashes with this FTP sys-module.

I previously tried with sys-ftpd light, and although it doesn't crash there, the connection drops all the time and I can't fix the broken pipe errors I receive when I try to sync, so I decided to give this one a try, but unfortunately it crashes the moment I use rclone to sync or bisync to the FTP server.

Here's the log from version 0.2.0: [log.txt](https://github.com/user-attachments/files/17961641/log.txt)

**Comment by ITotalJustice** [comment]
wow that log is strange. i think that log is caused due to how i handle files, i set the size in 1MiB increments, so the data in the file is completely random if it hasn't been written to yet :/

when you say the sysmod crashed, did the switch crash? or did ftpsrv stop responding?

**Comment by krasmazov483** [comment]
> when you say the sysmod crashed, did the switch crash? or did ftpsrv stop responding?

The second one, ftpsrv just stopped responding, every time it happens I have to reboot my Switch for it to work again.

> can you send the rclone command you used as well please? if i can reproduce it my end, it'll be much easier to fix.

Sure, I configured my Switch as a remote in rclone with the name `nx`, then tried using these commands:

`rclone -v bisync /home/jojo/.var/app/org.libretro.RetroArch/config/retroarch/saves/ nx:retroarch/cores/savefiles/ --resync`

_I have `--resync` at the end because the command was failing before with sys-ftpd light, but you shouldn't need it if you're doing it for the first time._

`rclone -v sync /home/jojo/.var/app/org.libretro.RetroArch/config/retroarch/saves/ nx:retroarch/cores/savefiles/`

**Comment by ITotalJustice** [comment]
thank you. i have fixed this locally. it seems to be an issue with the socket buffer size. i am trying to figure out the minimum amount of memory for bsd socket before i push a fix. in the meantime, you can use the application version or you can use this "fixed" version of the symod, but it will use a lot of memory. roughly ~300kib, but it will work with rclone.

transfer speed may be a bit slow, i can increase the buffer size etc for you if needed. I get 2MiB/s r/w with the sysmod.

you might want to enable `led=1` in the config as well, itll flash during any ftp operations.
[switch_sysmod.zip](https://github.com/user-attachments/files/17963598/switch_sysmod.zip)

**Comment by ITotalJustice** [comment]
Fixed in https://github.com/ITotalJustice/ftpsrv/commit/cd14ebba630db8e25a74f76b9ba5c05fcc24e8ae
If you have any further problems, feel free to open a new issue :)

Btw, the latest release is much faster than the version I posted here, I get 10mib/s read and 6mib/s write.
